# Feeds var.database of every consumer module (ADR 007) — by reference, never by value.
# All three names derive from cluster_name because the chart sets fullnameOverride from it,
# so nothing here has to ask the cluster what anything ended up being called.
#
# The Secret is generated by the chart and carries `username` and `password`. Host, port and
# database name are not secret and are published here instead of duplicated into it.
output "database" {
  value = {
    # In-cluster address, so always the service port. A NodePort adds a way in from outside
    # the cluster; it does not change how a consumer Pod reaches this.
    host_port   = "${var.cluster_name}.${var.namespace}.svc.cluster.local:5432"
    name        = var.initdb.database
    secret_name = var.cluster_name
  }
}
