# Feeds var.database of every consumer module (ADR 007) — by reference, never by value.
# The Secret is generated by CloudNativePG and carries username, password, host, port, dbname.
output "database" {
  value = {
    host_port   = "${var.cluster_name}-rw.${var.namespace}.svc.cluster.local:5432"
    name        = var.initdb.database
    secret_name = "${var.cluster_name}-app"
  }
}
